[firebase]
type = "service_account"
project_id = "hostellaundry-66895"
private_key_id = "fb6ee4dd50fc23caea58542ed707eb70c5710161"
client_email = "firebase-adminsdk-fbsvc@hostellaundry-66895.iam.gserviceaccount.com"
client_id = "107301445400439555264"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40hostellaundry-66895.iam.gserviceaccount.com"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDM303HP6kZCBVh
jQNlESsV7c1w7OOHv4VRspUVyuy1ryrhXGELxSo6wPXzc1lrSiZujh8/8iEGZI9F
4KdJrgEYlw08WO8YxU+VRvzF4NlKRdKqCWLf+Dj0yLNmMYttcWQCqDYg3YZJ4jBw
DPCqvkDakl9gFsOQqnxenT/jgbcifWCMC1VS7KpKdpfDHK8j5g3y4kYNxhRJL0Hd
LIYveodb5wdqOgJ2KvzitWWl9B272iBbnLE7uUfByoVEbgGq5NDm9tdV4Yq/RUBd
U90Qggo3C4pZCbhMpEnpjvaxuRo0+dsXBptLwtB+xkve8Tke9xpo57KnC/5H6lkm
+ClCC1UtAgMBAAECggEAFvMu5dKaUT0IFCD1T+WP84lrmapXxLWuLBw6ujG8uY+R
WKR+FJD2LZW/F5IE4tFwI7NVCddIXsx2BkhnxQeyhLwrFecKhbZYt2q31zzcaocO
1dBuXJOUYct32UtUiKKKpweL5LucFvu5HFw+u4nLfxClkYCLUNHgU8L+zLATwU+h
04Uho7sx8a9KE7w+rZBr61nH7ERDL53NmV16RJqwuoL3fr2sXfFfVaEYMl3TBKPH
FvG/y99Q7OXuG2vhI/5VA9N5lB6PHR/HwaJOn5FxRR6w/SZRbmoXZKSkpjRGW8Ue
q2rachX4rvB4WBayYit4QKAyTdy48EUdHByAQh+64QKBgQDyoLWcj9W+fxaR7Pkl
xx6c6By1xuvJ255ROxtcGOxEH21Fm2w8aBuB5JjQMhU95UIH140TKLHoDJbn648J
Ax/m16XZqSsHtQHc7tb6BJV3EyV39Oove4zFG0tTzVYMYEhXqz9oDDYprHtGMiXM
CQA6bsmsu/0i4FoJVZFmhNiXsQKBgQDYKeTBA4Aru7XP20DmfXdqNyeTB6TWFmz/
qAJ/L6V1CpY+7ri+PWxh8DNuDPNHCb0M3IhP/t6v9El17ncA45/8hKNA0GXZTX8t
eQ0i3Q5jGrG+xxvwooWX7INMl/Q3e1bRY71fHf1cQSheYgORdcr+T5GRcxGMi7R1
gT+Nu14wPQKBgGlpSx4HG60U2AB0PVadaP5wlbCgCOb9RI40KNHdfiCmqrnYKbEg
5fqMD5w8diAbD5IKox8Uyh5wAcwm+lDHC8AmJscnCSvjBzkuhzW+chV2uwuf23Lf
sawdDKAPEPh1iFiWbQjObWWzqyc3OFap/nBkm7gxQGw7nsJ5a59nzhYxAoGAWIY3
l0/usnpKB9ibqIjjWY1C2LS9ras7ciuE8j85/EecpiMvZ0FSXH15Im2NR59WW6kI
7fHLkrVxTCmfdK7Dey96h/WQcECLf7zeQ1PSK4XoGuABsjdsjH4ge0KTkhEhydiV
2hk3BAvvE1ACdBSQUDuXusAsBKnF+oU22L1N4mUCgYEA6EncUqBnQA4ybBCOWIK5
MOcK27YuroS8RiPF+GGvfFB1Eq9aTH6KdNJQfTkK2PTwt5s9qEVmgTUFtId3PX2a
hIZdAHLZxwfcAs4HTW5Smuscs/coOalOwLQJWXuAolbE4r4dwkd1D56G+7hs2OM2
WBW6h73N0lIB+StsbjNzM2A=
-----END PRIVATE KEY-----
"""
[general]
master_pin = "8888"
[telegram]
bot_token = "8512139904:AAENw2kqNWWfTK0i9JQvfTPOm-mlfyx2RSU"
chat_id = "-5065143511"
